server:
  port: 8080


spring:

  config:
    import: optional:file:.env[.properties]

  
  datasource:
    url: jdbc:postgresql://localhost:5432/billing_db
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernat:
      ddl-auto: create-delete
    properties:
      hibernate:
        format_sql: true;

  security:
    user:
      name: user1
      password: user1

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}

logging:
  level: 
    com.saas.billing_system.shared.context: TRACE

hello:
  world: 
