server:
  port: 8080


spring:

  config:
    import: optional:file:.env[.properties]

  
  datasource:
    url: jdbc:postgresql://localhost:5432/billing_db
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com

jwt:
  secret: ${JWT_SECRET}
logging:
  level: 
    com.saas.billing_system.shared.context: TRACE
    com.saas.billing_system: TRACE

