services:
    
  postgres:
    image: postgres
    container_name: billing_db_1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: billing_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: billing_cache_1
    ports:
      - "6379:6379"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
